version: "3.3"

services:
  mysqldb:
    container_name: mysqldb
    image: mysql:8
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: devopsdb        
    volumes:
      - /home/mysql/data:/var/lib/mysql
    ports:
      - "3306:3306"                   
    networks:
      - spring-network                

  spring_app:
    build: .
    container_name: devopscontainer
    restart: on-failure
    ports:
      - "9096:9096"
    depends_on:
      - mysqldb
    networks:
      - spring-network 
    environment:
      # CORRECTION ICI : Utilisation correcte des variables pour écraser application.properties
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/devopsdb?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      # Attention : C'est DRIVER_CLASS_NAME (avec des underscores), pas des tirets
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.MySQL8Dialect
      - SPRING_JPA_SHOW_SQL=true               
networks:
  spring-network: