version: '3.8'


.idea/services:

.vscode/  mysqldb:

*.iml    container_name: mysqldb

*.iws    image: mysql:8

*.ipr    restart: unless-stopped

.settings/    environment:

.classpath      MYSQL_ROOT_PASSWORD: root

.project      MYSQL_DATABASE: tpFoyer17

.git/    volumes:

.gitignore      - mysql_data:/var/lib/mysql

README.md    ports:

*.md      - '3306:3306'

.DS_Store    healthcheck:

      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  spring_app:
    build: .
    container_name: foyer-app
    restart: on-failure
    ports:
      - '8083:8083'
    depends_on:
      mysqldb:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/tpFoyer17?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

volumes:
  mysql_data:
