# Server configuration
server.servlet.context-path=/tpFoyer17
server.port=8082

### DATABASE ###
spring.datasource.url=jdbc:postgresql://db-test.postgres.database.azure.com:5432/testdb
spring.datasource.username=testuser
spring.datasource.password=SecretPwd123!
spring.datasource.driver-class-name=org.postgresql.Driver




### JPA / HIBERNATE ###
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
