# Server configuration
server.servlet.context-path=/tpFoyer17
server.port=8082

### DATABASE ###
spring.datasource.url=jdbc:postgresql://hh-pgsql-public.ebi.ac.uk:5432/pfmegrnargs
spring.datasource.username=reader
spring.datasource.password=NWDMCE5xdipIjRrp
spring.datasource.driver-class-name=org.postgresql.Driver

### JPA / HIBERNATE ###
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
