apiVersion: apps/v1
kind: Deployment
metadata:
  name: tpfoyer
  namespace: tpfoyer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tpfoyer
  template:
    metadata:
      labels:
        app: tpfoyer
    spec:
      containers:
        - name: tpfoyer
          image: IMAGE_TO_REPLACE
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://mysql-service.tpfoyer.svc.cluster.local:3306/tpfoyer"
            - name: SPRING_DATASOURCE_USERNAME
              value: "root"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "root"
---
apiVersion: v1
kind: Service
metadata:
  name: tpfoyer-service
  namespace: tpfoyer
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: tpfoyer
